function u = feedback_wrapper(feedback_model, feedback_params)
%  FEEDBACK WRAPPER Wrapper for feedback models so that they can be given
%  different parameters as needed while presenting a unified interface
%   Detailed explanation goes here
arguments (Input)
    feedback_model % feedback function {
                   %                    @basic_feedback
                   %                    @integral_feedback
                   %                    @no_feedback
                   %                   }
    feedback_params % a struct of filter parameters. Not all filter
end

arguments (Output)
    u % input to the system
end

model_name = func2str(feedback_model);
% decode feedback model and use the proper params
if strcmp(model_name, 'basic_feedback') % x_hat feedback
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.lin, ...
        feedback_params.setpoint);
elseif strcmp(model_name, 'integral_feedback') % x_hat feedback with x_I
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.x_I, ...
        feedback_params.lin, ...
        feedback_params.setpoint);
elseif strcmp(model_name, 'PI_feedback') % output feedback with x_I (requires an integrating observer)
    u = feedback_model( ...
        feedback_params.y, ...
        feedback_params.x_I, ...
        feedback_params.setpoint);
elseif strcmp(model_name, 'open_loop') % this will recalculate open loop u based on the nonlinear model)
    u = feedback_model( ...
        feedback_params.input_determination_function, ...
        feedback_params.setpoint, ...
        feedback_params.input);
elseif strcmp(model_name, 'no_feedback') % no feedback (unimplemented. Should I have it be 
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.x_I, ...
        feedback_params.lin, ...
        feedback_params.setpoint, ...
        feedback_params.strobe);
else
    u = NaN;
    disp("you gave feedback_wrapper (or full_differential_equation) a bad feedback_model name")

end