function u = feedback_wrapper(feedback_model, feedback_params)
%  FEEDBACK WRAPPER Wrapper for feedback models so that they can be given
%  different parameters as needed while presenting a unified interface
%   Detailed explanation goes here
arguments (Input)
    feedback_model % a function name
    feedback_params % a struct of filter parameters. Not all filter
end

arguments (Output)
    u % input to the system
end

model_name = func2str(feedback_model);
% decode feedback model and use the proper params
if strcmp(model_name, 'basic_feedback')
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.lin, ...
        feedback_params.setpoint);
elseif strcmp(model_name, 'integral_feedback')
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.integral_hat, ...
        feedback_params.lin, ...
        feedback_params.setpoint);
elseif strcmp(model_name, 'pid_feedback')
    u = feedback_model( ...
        feedback_params.x_hat, ...
        feedback_params.integral_hat, ...
        feedback_params.lin, ...
        feedback_params.setpoint, ...
        feedback_params.strobe);
else
    u = NaN;
    disp("you gave feedback_wrapper (or full_differential_equation) a bad feedback_model name")

end