function [x_hat_dot, x_I_dot] = observer_wrapper(observer_model, observer_params)
%  OBSERVER WRAPPER Wrapper for observer models so that they can be given
%  different parameters as needed while presenting a unified interface
%   Detailed explanation goes here
arguments (Input)
    observer_model % observer function {
                   %                    @basic_observer
                   %                    @integral_observer
                   %                    @saturating_integral_observer
                   %                    @integral_only
                   %                    @no_observer
                   %                   }
    observer_params % a struct of filter parameters. Not all filter
end

arguments (Output)
    x_hat_dot % estimated state
    x_I_dot % the predicted x_hat v. setpoint error, to be integrated
end

model_name = func2str(observer_model);
% decode observer model and use the proper params
if strcmp(model_name, 'basic_observer') % x_hat observer
    [x_hat_dot, x_I_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.lin, ...
        observer_params.y, ...
        observer_params.u);
elseif strcmp(model_name, 'integral_observer') % x_hat observer with x_I
    [x_hat_dot, x_I_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.x_I, ...
        observer_params.lin, ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.u);
elseif strcmp(model_name, 'saturating_integral_observer') % x_hat observer with x_I (saturating for anti-windup)
    [x_hat_dot, x_I_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.lin, ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.u);
elseif strcmp(model_name, 'integral_only') % x_I, no observer
    [x_hat_dot, x_I_dot] = observer_model( ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.x_I);
elseif strcmp(model_name, 'saturating_integral_only') % x_I, no observer (saturating for anti-windup)
    [x_hat_dot, x_I_dot] = observer_model( ...
        observer_params.setpoint, ...
        observer_params.y);
elseif strcmp(model_name, 'no_observer') % no observer, no x_I
    x_hat_dot = 0;
    x_I_dot = 0;
else
    x_hat_dot = NaN;
    x_I_dot = NaN;
    disp("you gave observer_wrapper (or full_differential_equation) a bad observer_model name")

end