function [x_hat_dot, integral_hat_dot] = observer_wrapper(observer_model, observer_params)
%  OBSERVER WRAPPER Wrapper for observer models so that they can be given
%  different parameters as needed while presenting a unified interface
%   Detailed explanation goes here
arguments (Input)
    observer_model % a function name
    observer_params % a struct of filter parameters. Not all filter
end

arguments (Output)
    x_hat_dot % estimated state
    integral_hat_dot % the predicted x_hat v. setpoint error, to be integrated
end

model_name = func2str(observer_model);
% decode observer model and use the proper params
if strcmp(model_name, 'basic_observer')
    [x_hat_dot, integral_hat_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.integral_hat, ...
        observer_params.lin, ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.u);
elseif strcmp(model_name, 'integral_observer')
    [x_hat_dot, integral_hat_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.integral_hat, ...
        observer_params.lin, ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.u);
elseif strcmp(model_name, 'saturating_integral_observer')
    [x_hat_dot, integral_hat_dot] = observer_model( ...
        observer_params.x_hat, ...
        observer_params.lin, ...
        observer_params.setpoint, ...
        observer_params.y, ...
        observer_params.u);
else
    x_hat_dot = NaN;
    integral_hat_dot = NaN;
    disp("you gave observer_wrapper (or full_differential_equation) a bad observer_model name")

end